language: python

python:
    - 2.7

# Install packages
install:
  # nose is pre-installed on Travis CI
  - pip install pyyaml
  - pip install nose-cov
  - pip install rednose
  - pip install coveralls

# Run tests
script:
  - nosetests -v --rednose --with-coverage --cover-package=respec test/*

after_success:
  - coveralls